language: rust
sudo: false
cache: cargo
rust:
  - 1.15.0
  - stable
  - beta
  - nightly-2017-04-28

env:
  global:
    - CLIPPY_VERSION=0.0.128
    - secure: "VM3IAyY5ye500pn9vFf0YbPMrUx87czHJbQ83vCL4cohLO4cQXpN5jf9RTo0dT5iP+1gY/biF1BMq3hshR3uPwFuKcTcYs8DrxSDfO18sG64yRJ7QAPNv9hrjhVzu3jk6w1kX3PlPbLykcj2GvCDR44Xyy7DEtaGot/hUrxbfZMdhM8YTEy+yiblgiI5iFOyx5+XACS8sNm9dJxbiIeN6sSi74QqLuhoWpDnBp8P+yPv0CWyRhX2ug7At8CPtigLi+YcxlVOWRxxQLcNXWjCsZuPYODkAGQ0TtJbkfiOXXz3mDGuE1cTw95mib4zJ5C7oEg3IWbLQ2lENylBhnZEsEPo/OUyW3jcbgzHUuDt+qKFKn7Bf2P5cOQA8dLim6IRExh1QCDm65z0Y3AhpsNX2wgN1Inf5uz0CK1O5kOHMT5YJCYKoYDDKGUanrbClUOk18L57DyLVDsVwx9MscrAPp4dqGBy1o6qDDKW1c/bWm9eSjAI7O6L/MN624oDM47R3CsqoS5ZUtyX7fifPSSdZCSZ+tvPan26EeVlty0BDEeHU4S8zImypLiGc7tTS5psb98Zt63dad7MoGCzIx79dJgQanA5RSl0Cd+fkK+gdnaTAe6LLDx2WXxySaW/NzWUf7Mz22EOrDMa9+yf9vWnxs+n+BXrkqEo8Jn+6C4vLdE="

before_script:
  - case "$TRAVIS_RUST_VERSION" in nightly*)
      cargo install clippy --vers $CLIPPY_VERSION --force;
    esac

script:
  - cargo test --all
  - case "$TRAVIS_RUST_VERSION" in nightly*)
      cargo clippy -- -D warnings;
      cd ./prom-attire-bootstrap; cargo clippy -- -D warnings; cd ..;
      cd ./prom-attire-impl; cargo clippy -- -D warnings; cd ..;
    esac

deploy:
  provider: script
  script: |
    cd ./prom-attire-impl
      cargo publish --token "$CRATES_IO_TOKEN"
    cd ../prom-attire-bootstrap
      cargo publish --token "$CRATES_IO_TOKEN"
    cd ..
    cargo publish --token "$CRATES_IO_TOKEN"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    condition: "$TRAVIS_RUST_VERSION = stable"
